version: '3.5'

services:
  app:
    container_name: app 
    image: azathe666/flats
    volumes:
      - static_value:/code/static/
    env_file:
      - .env
    ports:
      - '${APP_PORT}:3000'
  db:
    container_name: postgresql
    image: 'postgres:14'
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    depends_on:
      - app

volumes:
  postgres_data:
  static_value:
