version: "3.2"

services:

  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    image: azathe666/flats
    env_file:
      - .env
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - database

volumes:
  postgres_data:
