"""added

Revision ID: 7c0a751c3572
Revises: c2f4deb7d57d
Create Date: 2022-10-30 00:52:43.325220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0a751c3572'
down_revision = 'c2f4deb7d57d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flats', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flats', 'price')
    # ### end Alembic commands ###
