"""first

Revision ID: c2f4deb7d57d
Revises: 
Create Date: 2022-10-30 00:33:00.030877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f4deb7d57d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('metro_name', sa.String(), nullable=True),
    sa.Column('metro_time', sa.String(), nullable=True),
    sa.Column('metro_get_type', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('kitchen', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('constructed', sa.Integer(), nullable=True),
    sa.Column('fix', sa.String(), nullable=True),
    sa.Column('type_of_building', sa.String(), nullable=True),
    sa.Column('type_of_walls', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flats_id'), 'flats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flats_id'), table_name='flats')
    op.drop_table('flats')
    # ### end Alembic commands ###
