name: CI/CD webfastapi

on:
  push:
    branches: [ "tests" ]
  pull_request:
    branches: [ "tests" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
<<<<<<< HEAD
      - name: Test with pytest. Check health service and connect to database
=======
      - name: Test with pytest. Check health check
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
>>>>>>> 515a13d58f1d59d65347d20607feb1a8291898ce
        run: |
          poetry run python -m pytest --verbosity=2 --showlocals --log-level=DEBUG
