name: CI/CD webfastapi

on:
  push:
    branches: [ "tests" ]
  pull_request:
    branches: [ "tests" ]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Test with pytest. Check health check
        run: |
          poetry run python -m pytest --verbosity=2 --showlocals --log-level=DEBUG